ports:
  - 25 # smtp
  - 465 # smtps
  - 993 # imaps
  - 443 # https
  - 80 # http -> redirect to https
storage:
  type: s3
  bucket: "aukna-mail"
  accessKey: "admin"
  secretKey: "secret"
  endpoint: "aukna-mail.fsn1.your-objectstorage.com"
database:
  dsn: postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
